title: MIQA
description: QC processing
baseurl: '/'
markdown: kramdown

download_link: https://github.com/OpenImaging/miqa

# Footer Info
footer_license: 'Copyright Â© 2020 Kitware. All rights reserved.'
footer_links:
  # - title: Privacy Policy
  #   url: #
  # - title: Disclaimers
  #   url: #
  # - title: Contact
  #   url: 'https://www.kitware.com/contact-us/'

defaults:
  - scope:
      path: ''
    values:
      layout: 'default'

include: ['_pages']

exclude:
  - '*.config.js'
  - 'package*.json'
  - assets
  - node_modules
  - vendor
